WindowManager:
    Window1:
    Window2:

<Window1>:
    GridLayout:
        cols: 3
        size: root.width, root.height

        GridLayout:
            cols: 3

            Button:
                text: "Button 1"
                on_press: root.button_pressed(1)

            Button:
                text: "Button 2"
                on_press: root.button_pressed(2)

            Button:
                text: "Button 3"
                on_press: root.button_pressed(3)

            Button:
                text: "Button 4"
                on_press: root.button_pressed(4)

            Button:
                text: "Button 5"
                on_press: root.button_pressed(5)

            Button:
                text: "Button 6"
                on_press: root.button_pressed(6)

            Button:
                text: "Button 7"
                on_press: root.button_pressed(7)

            Button:
                text: "Button 8"
                on_press: root.button_pressed(8)

            Button:
                text: "Button 9"
                on_press: root.button_pressed(9)

<Window2>:
